spring.application.name=Practical1

#Databse connection H2 Databse :- 
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./data/practical1db
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Web Console - lets you view your database in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server Port
server.port=8000